apiVersion: v1
kind: Service
metadata:
  name: spring-gateway-book-service
  namespace: gateway-example
spec:
  selector:
    app: spring-gateway-book-app
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: http
  - port: 8081
    targetPort: 8081
    nodePort: 30081
    name: management
  - port: 8888
    targetPort: 8888
    nodePort: 30088
    name: jmx
