apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-gateway-edge-config
  namespace: gateway-example
data:
  application-deployed.yml: |+
    logging:
      request:
        verbose: true

  env: |+
    JAVA_OPTS=" \
            -Dcom.sun.management.jmxremote=true \
            -Dcom.sun.management.jmxremote.local.only=true \
            -Dcom.sun.management.jmxremote.port=8888 \
            -Dcom.sun.management.jmxremote.rmi.port=8888 \
            -Dcom.sun.management.jmxremote.ssl=false \
            -Dcom.sun.management.jmxremote.authenticate=false"
