apiVersion: v1
kind: Service
metadata:
  name: spring-gateway-edge
  namespace: gateway-example
spec:
  selector:
    app: spring-gateway-edge-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      name: http
    - port: 8081
      targetPort: 8081
      nodePort: 30081
      name: management
